### PR TITLE
Allow constructing the generator with a font from a reader

### PR DESCRIPTION
**Pull request by pete-woods**
### What did you implement:

Allow constructing the generator without needing to access the filesystem.

### How did you implement it:

Added a new constructor.

### How can we verify it:

The tests exercise both of the constructors.

### TODO's:

- [x] Write tests
- [x] Write documentation
- [x] Check that there aren't other open pull requests for the same issue/feature
- [x] Format your source code by `make fmt`
- [x] Provide verification config / commands
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

**Is this ready for review?:** Yes
**Is it a breaking change?:** No

### CODE REVIEW

**Comment by pete-woods** [comment]
@andyone do you have any time to give this PR a look over?

**Comment by andyone** [comment]
@pete-woods Hi! 

Sorry, your code doesn't follow the overall project code style and cannot be accepted to project code base. Please take a look on our [Contributing Guidelines](https://github.com/essentialkaos/contributing-guidelines?tab=readme-ov-file#code).

**Comment by pete-woods** [comment]
> @pete-woods Hi!
> 
> Sorry, your code doesn't follow the overall project code style and cannot be accepted to project code base. Please take a look on our [Contributing Guidelines](https://github.com/essentialkaos/contributing-guidelines?tab=readme-ov-file#code).

Any chance you can be a bit more specific? I've run `make fmt`, `make vet` and both come back with no changes.

Is it the named err return? If there's a better way you know of to handle not losing the file.Close error I'm quite happy to switch.

**Comment by andyone** [comment]
- PRs to `master` branch is not allowed
- Part of changed code becomes uncovered by tests
- We don't use named returns at all
- `w` is not valid parameter name for readers
- `ioutil.ReadAll` is deprecated since 1.16

**Comment by andyone** [comment]
Anyway I got the idea of your PR and have been implemented this in c3e33002428dd4966af8786af8670193ec319359.

**Comment by pete-woods** [comment]
Never mind - I see you merged something else!

**Comment by andyone** [comment]
Version [1.4.0](https://kaos.sh/go-badge/1.4.0) with this feature has been released.

**Pull request closed without merging**
